module.exports = {
  de:{
    timestring: function(time){
      return time.toLocaleString('de')+' Uhr'
    },
    open_tickets: 'Offene Tickets',
    closed_tickets: 'Geschlossene Tickets',
    tickets:'Tickets',
    ticket: 'Ticket',
    add_new_ticket:'Neues Ticket hinzufügen',
    list_open_tickets: 'Offene Tickets auflisten',
    list_closed_tickets: 'Geschlossene Tickets auflisten',
    search_ticket: 'Ticket suchen',
    search: 'suchen',
    change_user: 'User ändern',
    log_out: 'Log out',
    login: 'Login',
    ticket_number: 'ticketnr',
    title: 'Titel',
    tags: 'Tags',
    include:'must have',
    exclude: 'exclude',
    related_ticket: 'Zugehöriges ticket',
    published: 'Veröffentlicht',
    changed: 'Änderung',
    comments: 'Beiträge',
    last_comment: 'Letzter Beitrag',
    back_to_overview: 'zurück zur Übersicht',
    from: 'von',
    on: 'am',
    change_tags:'tags bearbeiten',
    cancel: 'abbrechen',
    images: 'Bilder',
    files: 'Dateien',
    add_comment:'Kommentar hinzufügen',
    close_ticket: 'Ticket schließen',
    reopen_ticket: 'Ticket öffnen',
    reply: 'hier antworten',
    add_files: 'bilder und dateien hinzufügen',
    submit: 'abschicken',
    ticket_is_closed:'Ticket ist geschlossen',
    name: 'name',
    password:'passwort',
    body:'Tickettext',
    new_ticket: 'neues ticket',
    comments:'Kommentare',
    userpage: 'Userpage',
    user: 'user',
    email: 'email',
    old_password: 'altes Passwort',
    new_password: 'neues Passwort',
    repeat_password: 'Passwort wiederholen',
    save: 'speichern',
  },
  es:{
    timestring: function(time){
      return time.toLocaleString('es')+'h'
    },
    open_tickets: 'boletos cerrados',
    closed_tickets: 'boletos abiertos',
    tickets:'boletos',
    ticket: 'boleto',
    add_new_ticket:'abre nuevo boleto',
    list_open_tickets: 'muestra boletos abiertos',
    list_closed_tickets: 'muestra boletos cerrados',
    search_ticket: 'buscar',
    search: 'buscar',
    change_user: 'usuario',
    log_out: 'cerrar sesion',
    login: 'iniciar sesion',
    ticket_number: 'no',
    title: 'titulo',
    tags: 'tags',
    include:'incluye',
    exclude: 'excluye',
    related_ticket: 'boleto relacionado',
    published: 'fecha publicado',
    changed: 'fecha cambiado',
    comments: 'comentarios',
    last_comment: 'ultimo comentario',
    back_to_overview: 'volver',
    from: 'de',
    on: 'en',
    change_tags:'cambia tags',
    cancel: 'aborta',
    images: 'imagenes',
    files: 'archivos',
    add_comment:'sube comentario',
    close_ticket: 'cerra boleto',
    reopen_ticket: 'abre boleto',
    reply: 'responde aqui',
    add_files:' sube imagenes y/o archivos',
    submit: 'subir',
    ticket_is_closed: 'boleto esta cerrado',
    name: 'nombre',
    password:'contraseña',
    body: 'body',
    new_ticket: 'nuevo boleto',
    comments:'comentarios',
    userpage: 'Userpage',
    user: 'usuario',
    email: 'correo electronico',
    old_password: 'contraseña actual',
    new_password: 'nueva contraseña',
    repeat_password: 'repite contraseña',
    save: 'guardar',
  },
  en:{
    timestring: function(time){
      return time.toLocaleString('en')
    },
    open_tickets: 'open tickets',
    closed_tickets: 'closed tickets',
    tickets:'tickets',
    ticket: 'ticket',
    add_new_ticket:'add new ticket',
    list_open_tickets: 'list open tickets',
    list_closed_tickets: 'list closed tickets',
    search_ticket: 'search',
    search: 'search',
    change_user: 'user',
    log_out: 'log out',
    login: 'Login',
    ticket_number: '#',
    title: 'title',
    tags: 'tags',
    include:'include',
    exclude: 'exclude',
    related_ticket: 'related ticket #',
    published: 'published',
    changed: 'changed',
    comments: 'comments',
    last_comment: 'last comment from',
    back_to_overview: 'back to overview',
    from: 'from',
    on: 'on',
    change_tags:'change tags',
    cancel: 'cancel',
    images: 'images',
    files: 'files',
    add_comment:'add comment',
    close_ticket: 'close ticket',
    reopen_ticket: 'reopen ticket',
    reply: 'reply',
    add_files: 'add_files',
    submit: 'submit',
    ticket_is_closed: 'ticket is closed',
    password:'password',
    name: 'name',
    body: 'body',
    new_ticket: 'new ticket',
    comments:'comments',
    user: 'user',
    email: 'email',
    old_password: 'current password',
    new_password: 'new password',
    repeat_password: 'repeat password',
    save: 'save',
  },
}
